
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [StringLength(50)]
        [Required(ErrorMessage ="This field is required.")]
        public string UserName { get; set; }
        [StringLength(50)]
        [DataType(DataType.Password)]
        [Required(ErrorMessage ="This field is required.")]
        public string Password { get; set; }

    }
}
