
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ListPro
{

    public int id { get; set; }
    
    [DisplayName("Products")]
    public int idList { get; set; }
    [DisplayName("Data")]
    public string doc { get; set; }



    public virtual Product Product { get; set; }

}

}
