
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {

        this.ListProes = new HashSet<ListPro>();

    }

    public int id { get; set; }
    [DisplayName("Id")]
    public int idList { get; set; }
    [DisplayName("Products")]
    public string name { get; set; }
    [DisplayName("Informations")]
    public string doc { get; set; }
    [DisplayName("Images")]
    public string img { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ListPro> ListProes { get; set; }

}

}
